service: sls-calc-backend

provider:
  name: aws
  runtime: python2.7

functions:

  get:
    handler: python-cost.python_cost_calculate
    events:
      - http:
          path: calc
          method: post
          cors: true


